name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          cd apps/worker
          pnpm install --frozen-lockfile

      - name: Run linting
        run: |
          cd apps/worker
          pnpm run lint

      - name: Run TypeScript check
        run: |
          cd apps/worker
          pnpm run type-check

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: lint-and-test
    # Only deploy on pushes to master, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          cd apps/worker
          pnpm install --frozen-lockfile

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "apps/worker"
          secrets: |
            TWITTER_BEARER_TOKEN
            TWITTER_CONSUMER_KEY
            TWITTER_CONSUMER_SECRET
            TWITTER_ACCESS_TOKEN
            TWITTER_ACCESS_TOKEN_SECRET
            UNDETECTABLE_AI_API_KEY
            TWITTER_WEBHOOK_SECRET
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          UNDETECTABLE_AI_API_KEY: ${{ secrets.UNDETECTABLE_AI_API_KEY }}
          TWITTER_WEBHOOK_SECRET: ${{ secrets.TWITTER_WEBHOOK_SECRET }} 